### ISSUE TITLE
Problems with .gitignore settings

### ISSUE THREAD

**Issue by odotom** [SublimeTextIssues/Merge#10]
Ignoring directories specified within .gitignore (without tailing slash) sometimes fails.

<img width="524" alt="bildschirmfoto 2018-09-21 um 00 43 45" src="https://user-images.githubusercontent.com/8082333/45851079-43053380-bd39-11e8-8010-ea1a1789aac9.png">

.gitgnore contains the directory name 'dist' .
Even though the directory is listed in .gitignore, Sublime Merge is showing files within 'dist' as untracked. 
Adding a slash ('dist' -> 'dist/') actually solves it.
Other directory names (eg. 'node-modules') are working properly without this hack and the files are ignored.
The command line version of git is working properly and does not show this behaviour

Debug information
MacOS X 10.13.6
=== App Version Information ===
Build: 1055

=== Git Version Information ===
Using Git: git
git version 2.17.1 (Apple Git-112)

=== Browse Page Information ===
HEAD: db378b0b27ae0c0150a4f3f7807249b2d5d07683
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===
?? dist/index.umd.js
?? dist/index.umd.js.map
?? dist/index.umd.min.js
?? dist/index.umd.min.js.map

=== Git Config Information ===
branch.master.merge=refs/heads/master
branch.master.remote=origin
core.bare=false
core.excludesfile=/Users/.../.gitignore_global
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
credential.helper=osxkeychain
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://...
...

=== Our Config Information ===
Git Config Path Information
Using config path: /etc/gitconfig
...

Our config output is different to the Git config output
branch.master.merge=refs/heads/master
branch.master.remote=origin
core.bare=false
core.excludesfile=/Users/.../.gitignore_global
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
...

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

**Comment by willrowe** [comment]
This may be related, I'm seeing an issue with a `.gitignore` file like this:

```bash
*
!.gitignore
!/sub_directory/
```

The files in `sub_directory` are being shown as untracked, but when running `git status` on the command line the working directory is clean. The only reason I discovered this is because my `.gitignore` file is wrong.

I was attempting to include the files in `sub_directory` like Sublime Merge is showing, but according to how gitignore is supposed to work (and how git on the command line is actually working) is that the `*` on line 1 affects the directory of the `.gitignore` file as well all sub directories as explained [here in the last example](https://git-scm.com/docs/gitignore#_examples).

If I change line 1 to `/*` or add `/sub_directory/**` to the end, command line git will include the files in the sub directory.

I posted this on [the forum as well](https://forum.sublimetext.com/t/sublime-merge/38962/51?u=willrowe).

**Comment by FichteFoll** [comment]
1058 was posted a couple days ago (and 1059 today). Does it fix any of the issues you were encountering?

**Comment by willrowe** [comment]
I can confirm that 1058 fixes my specific issue.

**Comment by odotom** [comment]
Yes, confirmed: 1058 fixes this issue
