### ISSUE TITLE
Allow smerge to be used as editor for git-difftool, git-mergetool

### ISSUE THREAD

**Issue by kebeda** [SublimeTextIssues/Merge#19]
Still use the command line a lot...would like the ability to use it as the editor that I have set for `git difftool` and `git mergetool` (or the -t option to the git diff and merge commands). See the "`-t <tool>`" section of:

https://git-scm.com/docs/git-difftool
https://git-scm.com/docs/git-mergetool

`ln -s /Applications/Sublime\ Merge.app/Contents/SharedSupport/bin/smerge /usr/local/bin/smerge`
`sudo launchctl config user path "/usr/local/bin:$PATH"`

**Comment by msjacoby23** [comment]
Thanks for the tip, @kebeda. I wasn't able to get this working. It's not clear to me how merge/diff.cmd should be configured in order to achieve what I'm looking for here. The `smerge` command help doesn't specify any instructions for parameters to use when initiating a merge or diff visualization and I wasn't able to find any elsewhere. Is this actually working for you? Maybe I'm misunderstanding your goal here. I was thinking the intention was to be able to, for example, use `git mergetool` when performing a merge that has a conflict and to have Sublime Merge open automatically and present the three-way merge tool UI for the relevant file...

**Comment by MareoRaft** [comment]
In order for `git mergetool` to launch Sublime Merge to resolve the current git merge conflicts, you need to put/link the `smerge` command into your PATH as kebeda has shown, then edit your `~/.gitconfig` to include:

    [merge]
            tool = "Sublime Merge"
    [mergetool "Sublime Merge"]
            cmd = smerge mergetool \"$BASE\" \"$REMOTE\" \"$LOCAL\" -o \"$MERGED\"

.  If you run `smerge --help` in your terminal, you will see further command line options that you can use to tweak the behavior.

For `git difftool`, it should be enough to open the repo with Sublime Merge, so the only thing I can recommend at this point is to simply run `smerge .` INSTEAD of `git difftool`.

**Comment by msjacoby23** [comment]
Thanks for the follow-up, @MareoRaft. I eventually realized after posting that when I entered merge or rebase via the CLI that required resolution, Sublime Merge was following along with git's state as I went, including offering its own resolution/diffing tools. That was good enough for me at the time, and usually still is. Now, with your additional guidance and also the changes to `smerge` in the most recent Sublime Merge version (Stable Channel, Build 1107), I will try again to configure `smerge` to use independently.

**Comment by davvid** [comment]
Is it still useful at all to add built-in support for `smerge` to `git mergetool` (or `difftool`)?  Just curious whether there's any desire to lower the friction to set this up.  We could upstream the config changes so that `git mergetool -t sublimemerge` works out of the box.

For example, it could automatically check in `/Applications/....` for the `smerge` script as a fallback when not found in the PATH.  That would eliminate the need for users to do that step.

If we think it's useful it's something we could upstream, but I don't have sublimemerge installed so I would need someone to help test it out.  The idea would be to get it added here: https://github.com/git/git/tree/master/mergetools so the config is built-in.  Useful?

**Comment by MareoRaft** [comment]
@davvid Well, it would be more convenient for people who are accustomed to using that `-t` option.  It also functions as documentation for how to combine git with smerge.

**Comment by davvid** [comment]
https://public-inbox.org/git/20190404073439.9558-1-davvid@gmail.com/#r

When that patch gets accepted `git mergetool -t smerge` and `git difftool -t smerge` will be builtin to git, and can be made the default using `git config --global merge.tool smerge`.

**Comment by davvid** [comment]
I believe this issue can now be closed.  Junio merged the `smerge` patch into `next` -- it'll likely get merged into master soon, and then it'll be part of the next feature release.

https://github.com/git/git/commit/eb12adc74cf22add318f884072be2071d181abaa

Usage:  `git config --global merge.tool smerge`  and then just `git mergetool` or `git difftool`.

**Comment by FichteFoll** [comment]
Indeed, this issue can be closed. See also the related but not the same issue https://github.com/sublimehq/sublime_merge/issues/40.

**Comment by 3v1n0** [comment]
> For git difftool, it should be enough to open the repo with Sublime Merge, so the only thing I can recommend at this point is to simply run smerge . INSTEAD of git difftool.

Mhmh, what if I'm using some more complex command line like diffing a subfolder from two tags?

In such case, it should be a difftool, as smerge . and then the diff args isn't working here.

**Comment by davvid** [comment]
@3v1n0 advanced difftool usage is well-handled by what landed in core Git.

https://github.com/git/git/blob/master/mergetools/smerge#L2
